### ISSUE TITLE
Why would I use stetho with a Cordova app? What are the uses cases?

### ISSUE THREAD

**Issue by janpio** [OutSystems/cordova-plugin-stetho-android#2]
Stetho looks neat, I want to play with it.

But: 
Why would I use stetho with a Cordova app? 
What are the actual use cases where this is helpful?

**Comment by Chuckytuh** [comment]
From the top of my head I would say that one application would be to easily inspect SQLite database from your cordova application... This plugin shines when used with the OutSystems platform giving some ability to troubleshoot some native functionalities that might be harder to do without the entire android/ios native development ecosystem.
